name: mdbook deploy to github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download mdbook for Lean
      uses: baptiste0928/cargo-install@v3
      with:
        crate: mdbook 
    - name: Run mdbook build
      shell: bash
      run: |
        mdbook build
        rm -rf ./out/.git
        rm -rf ./out/.github
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: out