[book]
authors = ["Archibald Neil MacDonald"]
language = "en"
multilingual = false
src = "src"
title = "Lean4 Commonplace Workbook"
description = "Personal workbook on solving Euler Lean4 problems"
git-repository-url = "https://github.com/aneilmac/euler-lean-book/tree/main/src"

[output.html]
mathjax-support = true

[preprocessor.alerts]