name = "Commonplace"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Commonplace", "EulerProblems"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Commonplace"

[[lean_lib]]
name = "EulerProblems"
